name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: ${{ secrets.FTP_SERVER }}
          repository_root: '/home/my_account/repositories/my_repository'
          branch: main
          cpanel_token: ${{ secrets.FTP_TOKEN }}
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
