name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: 'ftp.kendallryanlewis.com'
          repository_root: '/home/my_account/repositories/my_repository'
          branch: main
          cpanel_token: '9ZXY54XJXDL2QVNG3U5RH93ZVED1VLDT'
          cpanel_username: 'oalqr3yca8jb'
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
